{{- /*
Copyright 2026 GoodRx, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: {{ include "lifecycle-keycloak.fullname" . }}-lifecycle-realm
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lifecycle-keycloak.labels" (merge (dict "component" "keycloak") .) | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  keycloakCRName: {{ include "lifecycle-keycloak.fullname" . }}
  realm:
    realm: {{ .Values.realm | quote }}
    displayName: {{ .Values.realmDisplayName | quote }}
    enabled: true
    accessTokenLifespan: 300
    ssoSessionIdleTimeout: 36000
    ssoSessionMaxLifespan: 43200
    sslRequired: "external"
    loginTheme: "lifecycle"  # ref for login-theme-configmap.yaml
    accountTheme: "keycloak"
    adminTheme: "keycloak"
    emailTheme: "keycloak"

    # --- USERS ---
    users:
      - username: "service-account-lifecycle-ui-backend"
        enabled: true
        serviceAccountClientId: "lifecycle-ui-backend"
        realmRoles:
          - "default-roles-lifecycle"
        clientRoles:
          realm-management:
            - "view-users"
            - "query-users"

    # --- CLIENTS ---
    clients:
      - clientId: "broker"
        name: "${client_broker}"
        enabled: true
        bearerOnly: true
        protocol: "openid-connect"
        clientAuthenticatorType: "client-secret"
        attributes:
          realm_client: "true"
        defaultClientScopes: ["web-origins", "acr", "roles", "profile", "basic", "email"]
        optionalClientScopes: ["address", "phone", "offline_access", "organization", "microprofile-jwt"]

      - clientId: {{ .Values.clients.lifecycleCore.clientId | quote }}
        enabled: {{ .Values.clients.lifecycleCore.enabled }}
        publicClient: true
        webOrigins: ["+"]
        standardFlowEnabled: false
        directAccessGrantsEnabled: false
        fullScopeAllowed: true
        protocol: "openid-connect"
        defaultClientScopes: ["roles", "profile", "basic", "email"]

      - clientId: {{ .Values.clients.lifecycleUi.clientId | quote }}
        enabled: {{ .Values.clients.lifecycleUi.enabled }}
        clientAuthenticatorType: "client-secret"
        secret: {{ .Values.clients.lifecycleUi.clientSecret | quote }}
        redirectUris:
          - "{{ .Values.clients.lifecycleUi.url }}"
          - "{{ .Values.clients.lifecycleUi.url }}/"
          - "{{ .Values.clients.lifecycleUi.url }}/api/auth/callback/keycloak"
        webOrigins: ["+"]
        standardFlowEnabled: true
        protocol: "openid-connect"
        fullScopeAllowed: true
        attributes:
          backchannel.logout.session.required: "true"
        protocolMappers:
          - name: "Lifecycle core aud"
            protocol: "openid-connect"
            protocolMapper: "oidc-audience-mapper"
            config:
              included.client.audience: "lifecycle-core"
              access.token.claim: "true"
              introspection.token.claim: "true"

          - name: "Github profile picture"
            protocol: "openid-connect"
            protocolMapper: "oidc-usermodel-attribute-mapper"
            config:
              user.attribute: "githubProfilePicture"
              claim.name: "github_profile_picture"
              id.token.claim: "true"
              access.token.claim: "true"
              userinfo.token.claim: "true"
              jsonType.label: "String"

          - name: "Github username"
            protocol: "openid-connect"
            protocolMapper: "oidc-usermodel-attribute-mapper"
            config:
              user.attribute: "githubUsername"
              claim.name: "github_username"
              id.token.claim: "true"
              access.token.claim: "true"
              userinfo.token.claim: "true"
              jsonType.label: "String"
              introspection.token.claim: "true"

      - clientId: {{ .Values.clients.lifecycleUiBackend.clientId | quote }}
        enabled: {{ .Values.clients.lifecycleUiBackend.enabled }}
        clientAuthenticatorType: "client-secret"
        secret: {{ .Values.clients.lifecycleUiBackend.clientSecret | quote }}
        redirectUris: ["/*"]
        webOrigins: ["/*"]
        standardFlowEnabled: true
        serviceAccountsEnabled: true
        frontchannelLogout: true
        protocol: "openid-connect"
        attributes:
          frontchannel.logout.session.required: "true"
          backchannel.logout.session.required: "true"
        defaultClientScopes: ["web-origins", "service_account", "acr", "roles", "profile", "basic", "email"]
        optionalClientScopes: ["address", "phone", "offline_access", "organization", "microprofile-jwt"]

    # --- IDENTITY PROVIDERS ---
    identityProviders:
      - alias: "company-sso"
        providerId: "oidc"
        enabled: true
        updateProfileFirstLoginMode: "on"
        trustEmail: true
        config:
          # Internal SSO Provider
          clientId: {{ .Values.internalIdp.clientId | quote }}
          clientAuthMethod: "private_key_jwt"
          clientAssertionSigningAlg: "RS256"
          tokenUrl: {{ printf "%s/realms/%s/protocol/openid-connect/token" .Values.hostname .Values.internalIdp.realm | quote }}
          jwksUrl: {{ printf "%s/realms/%s/protocol/openid-connect/certs" .Values.hostname .Values.internalIdp.realm | quote }}
          authorizationUrl: {{ printf "%s/realms/%s/protocol/openid-connect/auth" .Values.hostname .Values.internalIdp.realm | quote }}
          logoutUrl: {{ printf "%s/realms/%s/protocol/openid-connect/logout" .Values.hostname .Values.internalIdp.realm | quote }}
          clientAssertionAudience: {{ printf "%s/realms/%s" .Values.hostname .Values.internalIdp.realm | quote }}
          defaultScope: "openid profile email"
          syncMode: "LEGACY"
          useJwksUrl: "true"
          sendIdTokenOnLogout: "true"
          validateSignature: "true"

          # External SSO Provider
          # clientAuthMethod: "client_secret_post"
          # tokenUrl: {{ .Values.companyIdp.tokenUrl | default (printf "%s/realms/company/protocol/openid-connect/token" .Values.hostname) | quote }}
          # jwksUrl: {{ .Values.companyIdp.jwksUrl | default (printf "%s/realms/company/protocol/openid-connect/certs" .Values.hostname) | quote }}
          # authorizationUrl: {{ .Values.companyIdp.authorizationUrl | default (printf "%s/realms/company/protocol/openid-connect/auth" .Values.hostname) | quote }}
          # logoutUrl: {{ .Values.companyIdp.logoutUrl | default (printf "%s/realms/company/protocol/openid-connect/logout" .Values.hostname) | quote }}
          # clientId: {{ .Values.companyIdp.clientId | default "${vault.company_idp_client_id}" | quote }}
          # clientSecret: {{ .Values.companyIdp.clientSecret | default "${vault.company_idp_client_secret}" | quote }}

      - alias: "github"
        providerId: "github"
        enabled: true
        updateProfileFirstLoginMode: "on"
        trustEmail: false
        storeToken: true
        linkOnly: true
        config:
          clientId: "${GITHUB_CLIENT_ID}" # {{ .Values.githubIdp.clientId | default .Values.secrets.githubClientId | quote }}
          clientSecret: "${vault.github-client-secret}" # {{ .Values.githubIdp.clientSecret | default .Values.secrets.githubClientSecret | quote }}
          syncMode: "LEGACY"

    identityProviderMappers:
      - name: "Github username"
        identityProviderAlias: "github"
        identityProviderMapper: "github-user-attribute-mapper"
        config:
          syncMode: "FORCE"
          userAttribute: "githubUsername"
          jsonField: "login"

      - name: "Github profile picture"
        identityProviderAlias: "github"
        identityProviderMapper: "github-user-attribute-mapper"
        config:
          syncMode: "FORCE"
          userAttribute: "githubProfilePicture"
          jsonField: "avatar_url"

    # --- COMPONENTS (USER PROFILE) ---
    components:
      org.keycloak.userprofile.UserProfileProvider:
        - providerId: "declarative-user-profile"
          config:
            kc.user.profile.config:
              - |
                {
                  "attributes": [
                    {
                      "name": "username",
                      "displayName": "${username}",
                      "validations": {
                        "length": { "min": 3, "max": 255 },
                        "username-prohibited-characters": {},
                        "up-username-not-idn-homograph": {}
                      },
                      "annotations": {},
                      "permissions": { "view": ["admin", "user"], "edit": ["admin"] },
                      "multivalued": false
                    },
                    {
                      "name": "email",
                      "displayName": "${email}",
                      "validations": { "email": {}, "length": { "max": 255 } },
                      "annotations": {},
                      "required": { "roles": ["user"] },
                      "permissions": { "view": ["admin", "user"], "edit": ["admin"] },
                      "multivalued": false
                    },
                    {
                      "name": "firstName",
                      "displayName": "${firstName}",
                      "validations": { "length": { "max": 255 }, "person-name-prohibited-characters": {} },
                      "annotations": {},
                      "required": { "roles": ["user"] },
                      "permissions": { "view": ["admin", "user"], "edit": ["admin"] },
                      "multivalued": false
                    },
                    {
                      "name": "lastName",
                      "displayName": "${lastName}",
                      "validations": { "length": { "max": 255 }, "person-name-prohibited-characters": {} },
                      "annotations": {},
                      "required": { "roles": ["user"] },
                      "permissions": { "view": ["admin", "user"], "edit": ["admin"] },
                      "multivalued": false
                    },
                    {
                      "name": "githubUsername",
                      "displayName": "${githubUsername}",
                      "validations": {},
                      "annotations": {},
                      "permissions": { "view": ["admin", "user"], "edit": ["admin"] },
                      "multivalued": false
                    },
                    {
                      "name": "githubProfilePicture",
                      "displayName": "${githubProfilePicture}",
                      "validations": {},
                      "annotations": {},
                      "permissions": { "view": ["admin", "user"], "edit": ["admin"] },
                      "multivalued": false
                    }
                  ],
                  "groups": [
                    {
                      "name": "user-metadata",
                      "displayHeader": "User metadata",
                      "displayDescription": "Attributes, which refer to user metadata"
                    }
                  ]
                }

    # --- AUTHENTICATION FLOWS ---
    browserFlow: "browser - idp only"
    authenticationFlows:
      - alias: "browser - idp only"
        description: "Browser based authentication"
        providerId: "basic-flow"
        topLevel: true
        authenticationExecutions:
          - authenticatorFlow: true
            flowAlias: "idp-only-main-logic"
            requirement: "REQUIRED"
            priority: 10

      - alias: "idp-only-main-logic"
        description: "Logic that groups cookie, redirect and organization"
        providerId: "basic-flow"
        topLevel: false
        authenticationExecutions:
          - authenticator: "auth-cookie"
            requirement: "ALTERNATIVE"
            priority: 10
          - authenticator: "identity-provider-redirector"
            requirement: "ALTERNATIVE"
            priority: 20
            authenticatorConfig: "company-sso"
          - authenticatorFlow: true
            flowAlias: "browser - idp only Organization"
            requirement: "ALTERNATIVE"
            priority: 30
          - authenticatorFlow: true
            flowAlias: "browser - idp only forms"
            requirement: "DISABLED"
            priority: 40

      - alias: "browser - idp only Organization"
        providerId: "basic-flow"
        topLevel: false
        authenticationExecutions:
          - authenticatorFlow: true
            requirement: "CONDITIONAL"
            priority: 10
            flowAlias: "browser - idp only Browser - Conditional Organization"
            userSetupAllowed: false

      - alias: "browser - idp only Browser - Conditional Organization"
        description: "Flow to determine if the organization identity-first login is to be used"
        providerId: "basic-flow"
        topLevel: false
        authenticationExecutions:
          - authenticator: "conditional-user-configured"
            requirement: "REQUIRED"
            priority: 10
          - authenticator: "organization"
            requirement: "ALTERNATIVE"
            priority: 20

      - alias: "browser - idp only forms"
        description: "Username, password, otp and other auth forms."
        providerId: "basic-flow"
        topLevel: false
        authenticationExecutions:
          - authenticator: "auth-username-password-form"
            requirement: "REQUIRED"
            priority: 10
          - authenticatorFlow: true
            requirement: "CONDITIONAL"
            priority: 20
            flowAlias: "browser - idp only Browser - Conditional 2FA"
            userSetupAllowed: false

      - alias: "browser - idp only Browser - Conditional 2FA"
        description: "Flow to determine if any 2FA is required for the authentication"
        providerId: "basic-flow"
        topLevel: false
        authenticationExecutions:
          - authenticator: "conditional-user-configured"
            requirement: "REQUIRED"
            priority: 10
          - authenticator: "auth-otp-form"
            requirement: "ALTERNATIVE"
            priority: 20
          - authenticator: "webauthn-authenticator"
            requirement: "DISABLED"
            priority: 30
          - authenticator: "auth-recovery-authn-code-form"
            requirement: "DISABLED"
            priority: 40

    authenticatorConfig:
      - alias: "company-sso"
        config:
          defaultProvider: "company-sso"
      - alias: "create unique user config"
        config:
          require.password.update.after.registration: "false"
      - alias: "review profile config"
        config:
          update.profile.on.first.login: "missing"

    requiredActions:
      - alias: "CONFIGURE_TOTP"
        name: "Configure OTP"
        providerId: "CONFIGURE_TOTP"
        enabled: false
        defaultAction: false
        priority: 10
      - alias: "UPDATE_PASSWORD"
        name: "Update Password"
        providerId: "UPDATE_PASSWORD"
        enabled: false
        defaultAction: false
        priority: 30
      - alias: "idp_link"
        name: "Linking Identity Provider"
        providerId: "idp_link"
        enabled: true
        defaultAction: false
        priority: 110
